### ISSUE TITLE
Exception missing setter under strict mode

### ISSUE THREAD

**Issue by sahanmal** [pupudu/my-sql#1]
var createPool = exports.createPool = _mysql.createPool;
                                    ^

TypeError: Cannot set property createPool of #<Object> which has only a getter
    at Object.<anonymous> 
(/node_modules/my-sql/dist/index.js:56:37)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (p/dist/app/databases/mysql/manager.js:1:142)
    at Module._compile (module.js:570:32)

**Comment by ow97** [comment]
I have this issue also, is there any workaround?

**Comment by pupudu** [comment]
@ow97 @sahanmal This is under development. The fix will be added within 24 hours from now.

**Comment by pupudu** [comment]
This issue is fixed in the latest version of my-sql
