### ISSUE TITLE
Changed import { <vars> } from 'my-sql'    to    var <var> = require('my-sql'); and problemns

### ISSUE THREAD

**Issue by jedusaad** [pupudu/my-sql#2]
By doing the conversion ( because im using express js on node) i get the problem "

> TypeError: Cannot set property createPool of #<Object> which has only a getter
    at Object.<anonymous> (E:\Servidores\api-kernel\node_modules\my-sql\dist\index.js:56:37)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (E:\Servidores\api-kernel\config\db.js:8:13)
    at Module._compile (module.js:643:30)

**Comment by pupudu** [comment]
This issue is fixed in the latest version
